/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2017-05-04 13:44:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Carm.GpDateConversion;
import java.util.List;
import Carm.EntityCard;
import Carm.DaoCarmPersonal;

public final class BKK010_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=UTF-8>\n");
      out.write("<title>クレジットカード管理システム</title>\n");
      out.write("<link href=\"./Main.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");

		Integer userId = (Integer) session.getAttribute("user_id");
		String userName = (String) session.getAttribute("user_name");
		
		DaoCarmPersonal dcp = new DaoCarmPersonal(userId);
		List<EntityCard> ecList = dcp.getCardEntity();
		GpDateConversion gdc = new GpDateConversion(new java.util.Date());
	
      out.write("\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<form action=\"./SvBKK010\" method=\"post\">\n");
      out.write("\t\t<h4>日付</h4>\n");
      out.write("\t\t<input type=\"text\" name=\"year\" value=");
      out.print(gdc.year);
      out.write(" class=\"sForm\">\n");
      out.write("\t\t年\n");
      out.write("\t\t<input type=\"text\" name=\"month\" value=");
      out.print(gdc.month);
      out.write(" class=\"sForm\">\n");
      out.write("\t\t月\n");
      out.write("\t\t<input type=\"text\" name=\"day\" value=");
      out.print(gdc.day);
      out.write(" class=\"sForm\">\n");
      out.write("\t\t日\n");
      out.write("\t\t<h4>金額</h4>\n");
      out.write("\t\t<input type=\"text\" name=\"payment\" class=\"mForm\">\n");
      out.write("\t\t円\n");
      out.write("\t\t<h4>カード</h4>\n");
      out.write("\t\t<SELECT name=\"card_id\">\n");
      out.write("\t\t\t<option value=\"\"></option>\n");
      out.write("\t\t\t");

				for (int j = 0; j < ecList.size(); j++) {
					int cardId = ecList.get(j).getCardId();
					String cardName = ecList.get(j).getCardName();
			
      out.write("\n");
      out.write("\t\t\t<option value=\"");
      out.print(cardId);
      out.write('"');
      out.write('>');
      out.print(cardName);
      out.write("</option>\n");
      out.write("\t\t\t");

				}
			
      out.write("\n");
      out.write("\t\t</SELECT>\n");
      out.write("\t\t<h4>摘要</h4>\n");
      out.write("\t\t<input type=\"text\" name=\"summary\" class=\"lForm\">\n");
      out.write("\t\t<br> <br>\n");
      out.write("\t\t<input type=\"submit\" value=\"記帳\" class=\"decision\">\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
