/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2017-05-07 11:52:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CMM030_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=UTF-8>\n");
      out.write("<title>クレジットカード管理</title>\n");
      out.write("<link href=\"./Main.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<script src=\"./jquery-3.2.0.min.js\"></script>\n");
      out.write("<script src=\"./Main.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
	
		Integer userId = (Integer) session.getAttribute("user_id");
		String type = (String) request.getAttribute("type");
		Integer result = (Integer) request.getAttribute("result");
		String alert = (String) request.getAttribute("alert");
		Integer updCnt = (Integer) request.getAttribute("upd_cnt");
		String style = null;
		String message = null;
	
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\n");
      out.write("\t<br>\n");
      out.write("\t");

		if (type != null) {
			if (type == "insert" || type == "update" || type == "delete") {
				if (result > 0) {
					style = "complete";
					message = "処理が完了しました";
				} else {
					style = "alert";
					message = "処理に失敗しました";
				}
			} else if (type == "error") {
				style = "alert";
				message = alert;
			}
		}

		if (updCnt != null && updCnt != 0) {
			style = "complete";
			message = "定期支払いを" + updCnt + "件 更新しました";
		}

		if (message != null) {
	
      out.write("\n");
      out.write("\t<div class=");
      out.print(style);
      out.write('>');
      out.print(message);
      out.write("</div>\n");
      out.write("\t");

		}
	
      out.write("\n");
      out.write("\t<div id=\"page\">\n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t<li><div class=\"edit-solid icon\"></div><a href=\"BKK010.jsp\">記帳</a>\n");
      out.write("\t\t\t<li><div class=\"eye icon\"></div><a href=\"CMM031.jsp\">照会</a></li>\n");
      out.write("\t\t\t<li><div class=\"tag icon\"></div><a href=\"CMM033.jsp\">用途管理</a></li>\n");
      out.write("\t\t\t<li><div class=\"card icon\"></div><a href=\"CMM032.jsp\">口座・カード管理</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<div></div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
